### PR TITLE
document Github (GFM) extensions

### PR DESCRIPTION
**Pull request by Crissov**
- based upon <https://github.com/github/cmark/blob/master/test/extensions.txt>
- will be split into modules in separate files:
    * Basic Pipe Tables
    * Strikethrough
    * Footnotes
    * Hashtags, Mentions and Plain Links
- also see the wiki:
    * [Deployed Extensions](https://github.com/commonmark/CommonMark/wiki/Deployed-Extensions) in existing implementations, which may not conform to CommonMark
    * [Proposed Extensions](https://github.com/commonmark/CommonMark/wiki/Proposed-Extensions) from threads on the Discourse site
    * ([Proposed Extensions to CommonMark](https://github.com/commonmark/CommonMark/wiki/Proposed-Extensions-to-CommonMark) list HTML and other features that people want to see supported without the syntax how it would be implemented)

### CODE REVIEW

**Comment by kivikakk** [comment]
This looks like it may duplicate effort already done in our adaptation of the spec? See https://github.github.com/gfm/.

**Comment by kivikakk** [comment]
It's worth noting too that @mentions and issue references (among many other things like sanitisation, image handling/proxying, etc.) are not implemented as part of the Markdown parser and so are not available in [our implementation](https://github.com/github/cmark).

Notably, footnotes are also not available as part of the regular GFM used on github.com.

**Comment by Crissov** [comment]
Yes, it is largely duplicating GitHub documentation for three reasons.

1. I was not aware of this fork of the Commonmark specification.
2. I found the documentation in the GitHub fork of `cmark` lacking detail and description.
3. I envision a set of modular extensions, probably in separate documents, that flavors can be build upon in a simple way.

I believe the first and the last point clearly speak in favor of centralizing the documentation of extensions and what better place than here?

**Comment by kivikakk** [comment]
1. It's linked in the opening paragraph of the `cmark-gfm` README ("the spec"), as well as our announcement blog post stating we were changing over to a CommonMark-based spec.
2. It's not intended as documentation; they're essentially defining the edges of the syntax for testing. The actual spec text ([which is indeed included in the repository](https://github.com/github/cmark/blob/master/test/spec.txt#L3243-L3260)) is the formal definition.
3. This is a fine thing to want 👍 

I'm a fan of centralising extensions, especially inasmuch as it might help encourage interoperability.

**Comment by Crissov** [comment]
I have changed course to document small extensions and then define flavors that merely list which extensions they are using and which restrictions or relaxations they may add.

**Pull request closed without merging**
